linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
linters:
  enable:
    - golint
    - govet
    - gofmt
    - goimports
    - structcheck
    - varcheck
    - interfacer
    - unconvert
    - ineffassign
    - goconst
    - gocyclo
    - maligned
    - misspell
    - nakedret
    - prealloc
    - gosec
    # TODO: Enable deadcode module once types are cleaned up
    #- deadcode
  disable-all: true
  # Run with --fast=false for more extensive checks
  fast: true
issue:
  max-same-issues: 0
  max-per-linter: 0
